[package]
name = "wasm-to-js-serde-molecule"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_molecule = "1.0.1"
wasm-bindgen = "0.2.93"
serde = { version = "1.0.208", default-features = false, features = ["derive"] }
serde-wasm-bindgen = "0.6.5"


[lib]
crate-type = ["cdylib"]
